set(CMAKE_SYSTEM_NAME Linux)
set(ARM ON)
set (PREFIX "/opt/hisi-linux/x86-arm/arm-himix200-linux/bin/arm-himix200-linux-")

set (CMAKE_STRIP ${PREFIX}strip CACHE FILEPATH "Strip")
set (CMAKE_NM  ${PREFIX}gcc-nm CACHE FILEPATH "NM")
set (CMAKE_RANLIB  ${PREFIX}gcc-ranlib CACHE FILEPATH "Ranlib")
set (CMAKE_AR ${PREFIX}gcc-ar CACHE FILEPATH "Archiver")
set (CMAKE_C_COMPILER ${PREFIX}gcc CACHE FILEPATH "GCC")
set (CMAKE_CXX_COMPILER ${PREFIX}g++ CACHE FILEPATH "G++")

message(STATUS "---------CMAKE_STRIP = ${CMAKE_STRIP}")
message(STATUS "---------CMAKE_NM = ${CMAKE_NM}")
message(STATUS "---------CMAKE_RANLIB = ${CMAKE_RANLIB}")
message(STATUS "---------CMAKE_AR = ${CMAKE_AR}")
message(STATUS "---------CMAKE_C_COMPILER = ${CMAKE_C_COMPILER}")
message(STATUS "---------CMAKE_CXX_COMPILER = ${CMAKE_CXX_COMPILER}")

SET(CMAKE_FIND_ROOT_PATH "...")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

add_definitions(-D__arm__)
add_definitions(-D__ARM_NEON__)
set(CPP11  "-std=c++11")
set(LAJI_DEV ON)
if (LAJI_DEV)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread -fvisibility=hidden -fPIC -O2 -ftree-vectorize -pipe -no-canonical-prefixes -march=armv7-a")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CPP11} -pthread -fpermissive -fvisibility=hidden -fPIC -O2 -ftree-vectorize -pipe -no-canonical-prefixes -march=armv7-a")
else()
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread -fvisibility=hidden -fPIC -O2 -ftree-vectorize -pipe -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -marm -mfpu=neon")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CPP11} -pthread -fpermissive -fvisibility=hidden -fPIC -O2 -ftree-vectorize -pipe -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -marm -mfpu=neon")
endif()

set(output_dir  "${CMAKE_CURRENT_SOURCE_DIR}/output")
set (bin_dir "${output_dir}/bin/arm_linux")
set (lib_dir "${output_dir}/lib/arm_linux")

if(NOT DEFINED CMAKE_LIBRARY_OUTPUT_DIRECTORY)
	set (CMAKE_LIBRARY_OUTPUT_DIRECTORY "${bin_dir}" CACHE STRING "" FORCE)
	message(STATUS "############set CMAKE_LIBRARY_OUTPUT_DIRECTORY : ${CMAKE_LIBRARY_OUTPUT_DIRECTORY} ")
endif()

if(NOT DEFINED CMAKE_RUNTIME_OUTPUT_DIRECTORY)
	set (CMAKE_RUNTIME_OUTPUT_DIRECTORY "${bin_dir}" CACHE STRING "" FORCE)
	message(STATUS "############set CMAKE_RUNTIME_OUTPUT_DIRECTORY : ${CMAKE_RUNTIME_OUTPUT_DIRECTORY} ")
endif()

if(NOT DEFINED CMAKE_ARCHIVE_OUTPUT_DIRECTORY)
	set (CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${lib_dir}" CACHE STRING "" FORCE)
	message(STATUS "############set CMAKE_ARCHIVE_OUTPUT_DIRECTORY : ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY} ")
endif()
