# set(CMAKE_SYSTEM_NAME Linux)
#set (PREFIX "/data/wensha2/tool/gcc-4.9.2-os7/bin/")
set (PREFIX "")
set (CMAKE_STRIP ${PREFIX}strip CACHE FILEPATH "Strip")
set (CMAKE_NM  ${PREFIX}gcc-nm CACHE FILEPATH "NM")
set (CMAKE_RANLIB  ${PREFIX}gcc-ranlib CACHE FILEPATH "Ranlib")
set (CMAKE_AR ${PREFIX}gcc-ar CACHE FILEPATH "Archiver")
set (CMAKE_C_COMPILER ${PREFIX}gcc CACHE FILEPATH "GCC")
set (CMAKE_CXX_COMPILER ${PREFIX}g++ CACHE FILEPATH "G++")

message(STATUS "---------CMAKE_SYSTEM_NAME = ${CMAKE_SYSTEM_NAME}")
message(STATUS "---------CMAKE_STRIP = ${CMAKE_STRIP}")
message(STATUS "---------CMAKE_NM = ${CMAKE_NM}")
message(STATUS "---------CMAKE_RANLIB = ${CMAKE_RANLIB}")
message(STATUS "---------CMAKE_AR = ${CMAKE_AR}")
message(STATUS "---------CMAKE_C_COMPILER = ${CMAKE_C_COMPILER}")
message(STATUS "---------CMAKE_CXX_COMPILER = ${CMAKE_CXX_COMPILER}")

set(CMAKE_FIND_ROOT_PATH "...")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

add_definitions(-D__X86_64__)
add_definitions(-D__SSE__)
set(CPP11  "-std=c++11")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread -m64 -fPIC -fvisibility=hidden -pipe -feliminate-unused-debug-types -DISS_EMNLU20_DEFINED -msse3 -msse4"  CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CPP11} -pthread -m64 -fPIC -fpermissive -fvisibility=hidden -pipe -feliminate-unused-debug-types -DISS_EMNLU20_DEFINED -msse3 -msse4"  CACHE STRING "" FORCE)
if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g -O0")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -O0")
else()
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O2"  CACHE STRING "" FORCE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2"  CACHE STRING "" FORCE)
endif()

# for sanitize ...
if(USE_SANITIZE)
    MESSAGE(STATUS "Just INTEL LINUX x64 supported ...")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g -fsanitize=address -fno-omit-frame-pointer -m64 -fPIC -fvisibility=hidden -pipe -feliminate-unused-debug-types -DISS_EMNLU20_DEFINED -msse3 -msse4")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CPP11} -g -fsanitize=address -fno-omit-frame-pointer -m64 -fPIC -fpermissive -fvisibility=hidden -pipe -feliminate-unused-debug-types -DISS_EMNLU20_DEFINED -msse3 -msse4")
endif()


set(output_dir  "${CMAKE_CURRENT_SOURCE_DIR}/output")
set (bin_dir "${output_dir}/bin/x86_64_linux")
set (lib_dir "${output_dir}/lib/x86_64_linux")

if(NOT DEFINED CMAKE_LIBRARY_OUTPUT_DIRECTORY)
	set (CMAKE_LIBRARY_OUTPUT_DIRECTORY "${bin_dir}")
	message(STATUS "############set CMAKE_LIBRARY_OUTPUT_DIRECTORY : ${CMAKE_LIBRARY_OUTPUT_DIRECTORY} ")
endif()

if(NOT DEFINED CMAKE_RUNTIME_OUTPUT_DIRECTORY)
	set (CMAKE_RUNTIME_OUTPUT_DIRECTORY "${bin_dir}")
	message(STATUS "############set CMAKE_RUNTIME_OUTPUT_DIRECTORY : ${CMAKE_RUNTIME_OUTPUT_DIRECTORY} ")
endif()

if(NOT DEFINED CMAKE_ARCHIVE_OUTPUT_DIRECTORY)
	set (CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${lib_dir}")
	message(STATUS "############set CMAKE_ARCHIVE_OUTPUT_DIRECTORY : ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY} ")
endif()
